[package]
name = "peeko"
version = "0.1.0"
edition = "2021"

[lib]
name = "peeko"
path = "src/lib.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1.0"
crossterm = "0.26"
ratatui = "0.20"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "2.1"
